In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [3]:
import yaml

with open('../config.yaml', 'r') as file:
    config = yaml.safe_load(file)

Opening both files using "yaml"

In [4]:
from pathlib import Path
import pandas as pd

base_path = Path("../config.yaml").parent
red_wines = pd.read_csv(base_path / config["input_data"]["file1"])
red_wines.head()

,Name,Country,Region,Winery,Rating,NumberOfRatings,Price,Year
0,Pomerol 2011,France,Pomerol,Château La Providence,4.2,100,95.00,2011
1,Lirac 2017,France,Lirac,Château Mont-Redon,4.3,100,15.50,2017
2,Erta e China Rosso di Toscana 2015,Italy,Toscana,Renzo Masi,3.9,100,7.45,2015
3,Bardolino 2019,Italy,Bardolino,Cavalchina,3.5,100,8.72,2019
4,Ried Scheibner Pinot Noir 2016,Austria,Carnuntum,Markowitsch,3.9,100,29.15,2016

In [5]:
red_wines.info()

<class 'pandas.DataFrame'>
RangeIndex: 8666 entries, 0 to 8665
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             8666 non-null   str
 1   Country          8666 non-null   str
 2   Region           8666 non-null   str
 3   Winery           8666 non-null   str
 4   Rating           8666 non-null   float64
 5   NumberOfRatings  8666 non-null   int64
 6   Price            8666 non-null   float64
 7   Year             8666 non-null   str
dtypes: float64(2), int64(1), str(5)
memory usage: 541.8 KB

In [6]:
wine_varieties = pd.read_csv(base_path / config["input_data"]["file2"])
wine_varieties.head()

        Variety
0      Abouriou
1     Abrustine
2      Absinthe
3  Acadie Blanc
4        Acolon

Extracting Variety out of Wine Names so it can be merged with Varieties.csv

In [7]:
common_varieties = wine_varieties["Variety"].unique()

def find_variety(name):
    for v in common_varieties:
        if v in name:
            return v
    return "Other"

red_wines["variety"] = red_wines["Name"].apply(find_variety)
red_wines.head()

,Name,Country,Region,Winery,Rating,NumberOfRatings,Price,Year,variety
0,Pomerol 2011,France,Pomerol,Château La Providence,4.2,100,95.00,2011,Other
1,Lirac 2017,France,Lirac,Château Mont-Redon,4.3,100,15.50,2017,Other
2,Erta e China Rosso di Toscana 2015,Italy,Toscana,Renzo Masi,3.9,100,7.45,2015,Other
3,Bardolino 2019,Italy,Bardolino,Cavalchina,3.5,100,8.72,2019,Other
4,Ried Scheibner Pinot Noir 2016,Austria,Carnuntum,Markowitsch,3.9,100,29.15,2016,Pinot Noir

Checking for null values

In [8]:
print(red_wines.isnull().sum())
print(wine_varieties.isnull().sum())
print(red_wines.isnull().mean() * 100)  # as percentages
print(wine_varieties.isnull().mean() * 100)  # as percentages

Name               0
Country            0
Region             0
Winery             0
Rating             0
NumberOfRatings    0
Price              0
Year               0
variety            0
dtype: int64
Variety    0
dtype: int64
Name               0.0
Country            0.0
Region             0.0
Winery             0.0
Rating             0.0
NumberOfRatings    0.0
Price              0.0
Year               0.0
variety            0.0
dtype: float64
Variety    0.0
dtype: float64

Counting Varieties in red_wines and understanding how many "others" there are. Merging might not be a good decision and "varieties" not needed.

In [11]:
red_wines["variety"].value_counts()

variety
Other                        5550
Cabernet Sauvignon            549
Merlot                        269
Pinot Noir                    260
Shiraz                        231
Brunello                      172
Syrah                         164
Malbec                        161
Primitivo                     120
Barbera                       119
Tempranillo                   110
Montepulciano                 107
Pinotage                       76
Nero d'Avola                   62
Zinfandel                      59
Zweigelt                       51
Blaufränkisch                  47
Negroamaro                     40
Lagrein                        39
Nebbiolo                       38
Sangiovese                     38
Dolcetto                       32
Aglianico                      31
Cabernet Franc                 30
Grenache                       24
Teroldego                      19
Carignan                       14
Tannat                         12
Susumaniello                   12
Corvina                        12
Mencia                         10
Parc                           10
Touriga                        10
Graciano                        7
Castiglione                     7
Garnatxa                        7
Carménère                       7
Mencía                          7
Bosco                           6
Malvasia                        6
St. Laurent                     6
Nerello Mascalese               6
Fer                             6
Sagrantino                      6
Italia                          5
Gin                             5
Refosco                         5
Dornfelder                      5
Mourvèdre                       4
Petit Verdot                    4
Lacrima                         3
Baga                            3
Petite Sirah                    3
Prieto Picudo                   3
Alicante Bouschet               3
Arbois                          3
Gloria                          3
Portugieser                     3
Diamond                         3
Gaglioppo                       3
Sankt Laurent                   2
Saperavi                        2
Bobal                           2
Blaufrankisch                   2
Boğazkere                       2
Plavac Mali                     2
Andre                           2
Perricone                       2
Frappato                        2
Vega                            2
Schioppettino                   2
Xinomavro                       2
Casetta                         2
Rebo                            2
Limnio                          1
Monastrell - Tempranillo        1
Agiorgitiko                     1
Tavkveri                        1
Mavro                           1
Optima                          1
Marselan                        1
Mission                         1
Alexander                       1
Tibouren                        1
Trincadeira                     1
Durif                           1
Samtrot                         1
Tazzelenghe                     1
Cabernet - Merlot - Syrah       1
Lambrusco                       1
Garnacha - Tempranillo          1
Raboso                          1
Caladoc                         1
Gamay                           1
Freisa                          1
Montu                           1
Flora                           1
Baco Noir                       1
Pais                            1
Marzemino                       1
Carmenere                       1
Monica                          1
Giro                            1
Brachetto                       1
Albarossa                       1
Name: count, dtype: int64

Merging datasets